# More option see https://github.com/DreamMaoMao/mango/wiki/

source=~/.config/mango/_monitor.conf
source=~/.config/mango/_env.conf
source=~/.config/mango/_autostart.conf
source=~/.config/mango/_appearance.conf
source=~/.config/mango/_animation.conf
source=~/.config/mango/_layout.conf
source=~/.config/mango/_misc.conf
source=~/.config/mango/_input.conf
source=~/.config/mango/_rule.conf
source=~/.config/mango/_keybind.conf
