#!/usr/bin/env bash

colors=(
"#f5e0dc"
"#f2cdcd"
"#f5c2e7"
"#cba6f7"
"#f38ba8"
"#eba0ac"
"#fab387"
"#f9e2af"
"#a6e3a1"
"#94e2d5"
"#89dceb"
"#74c7ec"
"#89b4fa"
"#b4befe"
"#cdd6f4"
"#bac2de"
"#a6adc8"
"#9399b2"
"#7f849c"
"#6c7086"
"#585b70"
"#45475a"
"#313244"
"#1e1e2e"
"#181825"
"#11111b"
)

hex_to_rgb() {
    local hex=${1#"#"}
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "$r;$g;$b"
}

for hex in "${colors[@]}"; do
    rgb=$(hex_to_rgb "$hex")
    printf "\e[48;2;%sm      \e[0m %s\n" "$rgb" "$hex"
done
