#!/usr/bin/env bash

colors=(
"#191724"
"#1f1d2e"
"#26233a"
"#6e6a86"
"#908caa"
"#e0def4"
"#eb6f92"
"#f6c177"
"#ebbcba"
"#31748f"
"#9ccfd8"
"#c4a7e7"
"#21202e"
"#403d52"
"#524f67"
)

hex_to_rgb() {
    local hex=${1#"#"}
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "$r;$g;$b"
}

for hex in "${colors[@]}"; do
    rgb=$(hex_to_rgb "$hex")
    printf "\e[48;2;%sm      \e[0m %s\n" "$rgb" "$hex"
done
