hl.on("hyprland.start", function ()
    hl.exec_cmd("~/.config/hypr/scripts/xdph.sh")
    -- hl.exec_cmd("dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("/usr/libexec/hyprpolkitagent")
    hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "Dracula"')
    hl.exec_cmd('gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"')
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dbus-launch dunst -config $HOME/.config/dunst/dunstrc")
    hl.exec_cmd("pipewire")
    hl.exec_cmd("wireplumber")
    hl.exec_cmd("pipewire -c pipewire-pulse.conf")
    hl.exec_cmd("~/.config/hypr/scripts/audio-autoswitch.sh")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("dbus-launch waybar")
    hl.exec_cmd("dbus-launch /usr/lib/xfce4/xfconf/xfconfd")
    hl.exec_cmd("udiskie --automount --no-notify --no-tray")
end)
