require("_monitor")
pcall(require, "_monitor_state")
require("_env")
require("_autostart")
require("_appearance")
require("_animation")
require("_misc")
require("_input")
require("_keybind")
require("_rule")
