#! /bin/sh

export XDG_CURRENT_DESKTOP='bspwm'

# Java Applications Fix
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

pidof -q sxhkd || { sxhkd -c $HOME/.config/bspwm/sxhkdrc & }
pidof -q nm-applet || { nm-applet & }
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }
$HOME/.config/polybar/launch.sh
pidof -q feh || feh --bg-fill $HOME/Pictures/Wallpapers/aesthetic-cityscape-sunset-bridge-desktop-wallpaper-4k.jpg
pidof -q fcitx5 || { fcitx5 & }
pidof -q picom || { picom & }
pidof -q dunst || { dunst -config $HOME/.config/dunst/dunstrc & }

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc monitor DP-2 -d 1 2 3 4
# bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config active_border_color \#585b70
bspc config normal_border_color \#585b70
bspc config focused_border_color \#89b4fa

bspc rule -r *:*

bspc config external_rules_command "${HOME}"/.config/bspwm/ext-rules

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Minecraft state=floating center=true
# bspc rule -a PrismLauncher state=floating center=true
# bspc rule -a minecraft-launcher state=floating center=true
bspc rule -a clapper state=floating
bspc rule -a loupe state=floating
bspc rule -a org.gnome.Nautilus state=floating center=true
bspc rule -a easyeffects state=floating
bspc rule -a obs state=floating center=true
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# declare -a games=(Minecraft minecraft-launcher PrismLauncher)
# for i in ${games[@]}; do
#    bspc rule -a $i state=floating center=true follow=on focus=on; done
