#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/Wallpapers/aesthetic-cityscape-sunset-bridge-desktop-wallpaper-4k.jpg
fcitx5 &
picom
dunst -config $HOME/.config/dunst/dunstrc

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc monitor DP-2 -d 1 2 3 4
# bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config active_border_color \#595959
bspc config normal_border_color \#595959
bspc config focused_border_color \#33ccff

# Java Applications Fix
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Minecraft state=floating
bspc rule -a MiltiMC state=floating
bspc rule -a clapper state=floating
bspc rule -a nautilus state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
