-- Generated by monitor-switch (Extend). Do not edit by hand.
hl.monitor({
    output = "eDP-1",
    mode = "highrr",
    position = "0x0",
    scale = 1,
    disabled = false,
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@75",
    position = "1920x0",
    scale = 1.25,
    disabled = false,
})
