-- Generated by ~/scripts/theme (Tokyo Night, dark) -- do not edit by hand.
-- Sourced by the hyprland config so notify-send markup follows the active theme.

return {
    name = "Tokyo Night",
    mode = "dark",
    bg = "#1a1b26",
    bg_alt = "#24283b",
    surface = "#414868",
    fg = "#c0caf5",
    fg_dim = "#a9b1d6",
    fg_muted = "#565f89",
    red = "#f7768e",
    green = "#9ece6a",
    yellow = "#e0af68",
    blue = "#7aa2f7",
    purple = "#bb9af7",
    aqua = "#7dcfff",
    orange = "#ff9e64",
}
