hl.on("hyprland.start", function ()
    hl.exec_cmd("~/.config/hypr/scripts/xdph.sh")
    hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "Dracula"')
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dunst -config $HOME/.config/dunst/dunstrc")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("systemctl --user start pipewire pipewire-pulse wireplumber")
    hl.exec_cmd("easyeffects --hide-window --service-mode")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("waybar")
    hl.exec_cmd("udiskie --automount --no-notify --no-tray")
end)
